### ISSUE TITLE
Typo in PersonByAliasGuid Example

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/RockWebsites#20]
### Website Issue Report

**URL:** https://community.rockrms.com/lava/filters/person-filters

**Description of Issue**

Current Description Is:
{% assign campusLeader = **Campus.LeaderPersonAliasId** | PersonByAliasGuid %}

Hello {{ campusLeader.NickName }}!

I believe correct description should be:
{% assign campusLeader = **Campus.LeaderPersonAlias.Guid** | PersonByAliasGuid %}

Hello {{ campusLeader.NickName }}!

**Comment by cabal95** [comment]
Fixed, thanks for reporting!

It actually (based on the example data) should have been `Campus.LeaderPersonAliasGuid`.

**Comment by bscottdavis** [comment]
Thanks!
I'm not seeing LeaderPersonAliasGuid in the Model Map for Campus. I just did a quick test in my lava tester and it looks like Campus.LeaderPersonAliasGuid doesn't work but Campus.LeaderPersonAlias.Guid does work. Can you double check?


![IdorGuid](https://user-images.githubusercontent.com/605691/59056366-e1e0aa00-884c-11e9-8e86-b3e2f91b113d.png)

**Comment by cabal95** [comment]
It doesn't exist, it is a contrived example (but as you originally pointed out was not correct). Not all the examples follow the real database model map because they need to show the possible uses in a way that is easy to understand. The normal way you would use `PersonByAliasGuid` would be with a Person attribute, but that example gets rather convoluted quickly because you are throwing a number of different Lava features in all at once (for example, you would need to use the `RawValue` qualifier).

In this example, just above the Lava code, you can see what is (for example purposes) available as variables:

<img width="683" alt="Screen Shot 2019-06-06 at 11 29 51 AM" src="https://user-images.githubusercontent.com/1119863/59057130-8fa08880-884e-11e9-9795-927b1ede075e.png">

So for the purposes of this example, we are assuming there is an object called `Campus` with a property of `LeaderPersonAliasGuid`.

A real world example would probably be something like:

```
{% assign campusLeader = campus | Attribute:'LeaderPerson','RawValue' | PersonByAliasGuid %}

Hello {{ campusLeader.NickName }}
```

But as I mentioned we are then adding multiple things for them to learn all at once rather than just this one filter - and we are still in the same boat of it being a contrived example, because there is not actually a `LeaderPerson` attribute on the campus either.

Hope  this helps!

**Comment by bscottdavis** [comment]
Gotcha, it totally makes sense the example illustrates how the Filter works, not necessarily how the database is structured. Thanks for making the update!
