### ISSUE TITLE
Can't login to Community.rock (no error or anything)

### ISSUE THREAD

**Issue by adammaclaren** [SparkDevNetwork/RockWebsites#52]
### Website Issue Report

**URL:** https://community.rockrms.com/

**Description of Issue**
I am trying to login to my profile and it shows the progress icon and then just takes me back to the previous page I was on before I clicked login. No error or anything. This appears to be happening in Chrome.

**Comment by cabal95** [comment]
Hi @adammaclaren, this is probably due to a glitch that occurred a few weeks ago. You will probably have to check your browser cookies (it's different in each browser, but probably under Developer Tools somewhere) and remove any `.ROCK` cookies for the `rockrms.com` site(s). Then it should let you login.

**Comment by garrettjohnson** [comment]
@adammaclaren Before clearing your cache, could you take a screenshot of your cookies via https://developers.google.com/web/tools/chrome-devtools/storage/cookies and email it to me, garrett@sparkdevnetwork.org Thanks!!
