### ISSUE TITLE
iOS 14.8.1 - Safari - Log in Issue 

### ISSUE THREAD

**Issue by jaimebailey** [SparkDevNetwork/RockWebsites#81]
### Website Issue Report

https://rock.reallifeministries.com/page/3?returnurl=%252f

**Description of Issue**
When attempting to log in with credentials that are saved in iOS's credential management, we are directed to a page stating "Can't log in? Enter your email address " with an "Email me reset instructions" button. The credentials are correct, and we have replicated the issue on multiple devices with multiple accounts. Issue has not happened on windows 10 devices, or on google chrome for iOS. 

_please provide as much detail as possible_

**Comment by jonedmiston** [comment]
Hi @jaimebailey ! This repo is for issues relating to the content on the Spark / Rock websites. Sounds like this is an issue in the Rock Core code. Could you:

1. Verify that you get the same issue on the Demo (https://rock.rocksolidchurchdemo.com/) or Pre-alpha sites (https://prealpha.rocksolidchurchdemo.com/) (this would assure that that problem is not local to your theme).
2. Assuming you can confirm the results then open an issue in the core Github repo here: https://github.com/SparkDevNetwork/Rock/tree/develop
